[features]
seeds = false
[programs.localnet]
nabittuto = "3SFNFgpmm6JEtKg4B2mmoBSDQYojxogi9jH46m6fKbgf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/doms/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
